include:
  # use frontend-ci
  - project: aric.zheng/frontend-ci
    ref: master
    file: dist/templates/react-oss/main.yml

variables:
  BUCKET_CONTEXT: biotech-site-predict-frontend/<%= project_name %>
